bf:
	../cpi bf.cpi -o bf.out --binary

bf_test: bf
	./runbf.sh "++++++++++[>+++++++>++++++++++>+++>+<<<<-]>++.>+.+++++++..+++.>++.<<+++++++++++++++.>.+++.------.--------.>+.>."


tictactoe :
	../cpi tictactoe.cpi -o tictactoe.out --binary

.PHONY : clean
clean :
	rm -f *.out

