bf:
	../cpi bf.cpi -o bf.out --binary

bf_test: bf
	./runbf.sh "++++++++++[>+++++++>++++++++++>+++>+<<<<-]>++.>+.+++++++..+++.>++.<<+++++++++++++++.>.+++.------.--------.>+.>."


tictactoe :
	../cpi tictactoe.cpi -o tictactoe.out --binary

ll:
	../cpi linked_list.cpi -o linked_list.out --binary -tc

.PHONY : clean
clean :
	rm -f *.out

